version: "3.9"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysqldb
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  adminer:
    depends_on:
      - mysqldb
    image: adminer:latest
    container_name: adminer
    ports:
      - "88:8080"
    restart: always
volumes:
  db_data:
    external: true
  wordpress_data:
    external: true
